// shortcuts to common locations
// For earlier versions each HELP_URL() entry ended with ".htm".  For 20.0 onwards, the browser URLs (see help.c) end with "/" 
// rather than ".htm":  it's easier to add "/" or ".htm" as appropriate rather than have to alter one to the other.

#define CS 	"programming-reference-guide/defined-functions-and-operators/traditional-functions-and-operators/control-structures"
#define SY 	"language-reference-guide/symbols"
#define OO 	"programming-reference-guide/object-oriented-programming"
#define OP 	"language-reference-guide/primitive-operators"
#define SYS "language-reference-guide/system-commands"
#define GY 	"language-reference-guide/glyphs"
#define QUAD	"language-reference-guide/system-functions"

#define PROP 	"object-reference/properties"
#define OBJ 	"object-reference/objects"
#define EVENT 	"object-reference/methodorevents"

// Control Structures

// the following two URLS are the same, but one uses the CS shortcut
HELP_URL(":if"		,"programming-reference-guide/defined-functions-and-operators/traditional-functions-and-operators/control-structures/if")
HELP_URL(":else"	,CS"/if")

HELP_URL(":orif"	,CS"/if")
HELP_URL(":andif"	,CS"/if")
HELP_URL(":endif"	,CS"/if")

HELP_URL(":elseif"	,CS"/control-structures-summary")
HELP_URL(":else"	,CS"/control-structures-summary")
HELP_URL(":end"		,CS"/control-structures-summary")

HELP_URL(":while"	,CS"/while")
HELP_URL(":endwhile"	,CS"/while")

HELP_URL(":repeat"	,CS"/repeat")
HELP_URL(":until"	,CS"/repeat")
HELP_URL(":endrepeat"	,CS"/repeat")

HELP_URL(":for"		,CS"/for")
HELP_URL(":in"		,CS"/for")
HELP_URL(":ineach"	,CS"/for")
HELP_URL(":endfor"	,CS"/for")

HELP_URL(":select"	,CS"/select")
HELP_URL(":case"	,CS"/select")
HELP_URL(":caselist"	,CS"/select")
HELP_URL(":endselect"	,CS"/select")

HELP_URL(":hold"	,CS"/hold")
HELP_URL(":endhold"	,CS"/hold")

HELP_URL(":with"	,CS"/with")
HELP_URL(":endwith"	,CS"/with")

HELP_URL(":trap"	,CS"/trap")
HELP_URL(":endtrap"	,CS"/trap")

HELP_URL(":disposable"	,CS"/disposable")
HELP_URL(":enddisposable",CS"/disposable")

HELP_URL(":goto"	,CS"/goto")
HELP_URL(":continue"	,CS"/continue")
HELP_URL(":leave"	,CS"/leave")
HELP_URL(":return"	,CS"/return")

HELP_URL(":access"	,CS"/access")
HELP_URL(":implements"	,CS"/implements")
HELP_URL(":signature"	,CS"/signature")
HELP_URL(":attribute"	,CS"/attribute")
HELP_URL(":using"	,CS"/using")

HELP_URL(":require"	,OO"/including-script-files")
HELP_URL(":field"	,OO"/field-statement")
HELP_URL(":property"	,OO"/property-section/property-section")
HELP_URL(":endproperty"	,OO"/property-section/property-section")
HELP_URL(":include"	,OO"/including-namespaces-in-classes/including-namespaces-in-classes")

HELP_URL(":class"	,CS"/class")
HELP_URL(":endclass"	,CS"/class")

HELP_URL(":section"	,CS"/section")
HELP_URL(":endsection"	,CS"/section")

HELP_URL(":namespace"	,CS"/namespace")
HELP_URL(":endnamespace",CS"/namespace")

HELP_URL(":interface"	,CS"/interface")
HELP_URL(":endinterface",CS"/interface")


// Primitives

HELP_URL("⌶"	,OP"/i-beam/index")
HELP_URL("\'"	,GY)
HELP_URL("⍺"	,GY)
HELP_URL("⍵"	,GY)
HELP_URL("_"	,GY)
HELP_URL("¯"	,GY)
HELP_URL("."	,SY"/dot")
HELP_URL("⍬"	,SY"/zilde")
HELP_URL("⊢"	,SY"/right-tack")
HELP_URL("∆"	,GY)
HELP_URL("⍙"	,GY)
HELP_URL("{"	,GY)
HELP_URL("}"	,GY)
HELP_URL("⊣"	,SY"/left-tack")
HELP_URL("⌷"	,SY"/squad")
HELP_URL("¨"	,SY"/diaeresis")
HELP_URL("⍨"	,SY"/tilde-diaeresis")
HELP_URL("["	,GY)
HELP_URL("/"	,SY"/slash")
HELP_URL("⌿"		,SY"/slash-bar")
HELP_URL("\\"	,SY"/backslash")
HELP_URL("⍀"		,SY"/backslash-bar")
HELP_URL("<"	,SY"/less-than")
HELP_URL("≤"	,SY"/less-than-or-equal-to")
HELP_URL("="	,SY"/equal")
HELP_URL("≥"	,SY"/greater-than-or-equal-to")
HELP_URL(">"	,SY"/greater-than")
HELP_URL("≠"	,SY"/not-equal")
HELP_URL("∨"	,SY"/logical-or")
HELP_URL("∧"	,SY"/logical-and")
HELP_URL("-"	,SY"/minus")
HELP_URL("+"	,SY"/plus")
HELP_URL("÷"	,SY"/divide")
HELP_URL("×"	,SY"/times")
HELP_URL("?"	,SY"/question-mark")
HELP_URL("∊"	,SY"/epsilon")
HELP_URL("⍴"	,SY"/rho")
HELP_URL("~"	,SY"/tilde")
HELP_URL("↑"	,SY"/up-arrow")
HELP_URL("↓"	,SY"/down-arrow")
HELP_URL("⍳"		,SY"/iota")
HELP_URL("○"	,SY"/circle")
HELP_URL("*"	,SY"/star")
HELP_URL("⌈"	,SY"/upstile")
HELP_URL("⌊"	,SY"/downstile")
HELP_URL("∇"	,GY)
HELP_URL("∘"		,SY"/jot")
HELP_URL("⍛"    ,SY"/jot-underbar")
HELP_URL("("	,GY)
HELP_URL("⊂"	,SY"/left-shoe")
HELP_URL("⊃"	,SY"/right-shoe")
HELP_URL("∩"	,SY"/up-shoe")
HELP_URL("∪"	,SY"/down-shoe")
HELP_URL("⊥"	,SY"/up-tack")
HELP_URL("⊤"	,SY"/down-tack")
HELP_URL("|"	,SY"/stile")
HELP_URL(";"	,GY)
HELP_URL(","	,SY"/comma")
HELP_URL("⍱"	,SY"/logical-nor")
HELP_URL("⍲"	,SY"/logical-nand")
HELP_URL("⍒"	,SY"/grade-down")
HELP_URL("⍋"	,SY"/grade-up")
HELP_URL("⍉"	,SY"/circle-backslash")
HELP_URL("⌽"	,SY"/circle-stile")
HELP_URL("⊖"	,SY"/circle-bar")
HELP_URL("⍟"	,SY"/log")
HELP_URL("⌹"	,SY"/domino")
HELP_URL("!"	,SY"/exclamation-mark")
HELP_URL("⍕"	,SY"/thorn")
HELP_URL("⍎"	,SY"/hydrant")
HELP_URL("⍫"	,GY)
HELP_URL("⍪"		,SY"/comma-bar")
HELP_URL("≡"	,SY"/equal-underbar")
HELP_URL("≢"	,SY"/equal-underbar-slash")
HELP_URL("#"	,GY)
HELP_URL("&"	,SY"/ampersand")
HELP_URL("@"	,SY"/at")
HELP_URL(":"	,GY)
HELP_URL("⍷"		,SY"/epsilon-underbar")
HELP_URL("⋄"	,"programming-reference-guide/defined-functions-and-operators/traditional-functions-and-operators/statements")
HELP_URL("←"	,SY"/left-arrow")
HELP_URL("→"	,SY"/right-arrow")
HELP_URL("⍝"	,"programming-reference-guide/defined-functions-and-operators/traditional-functions-and-operators/statements")
HELP_URL(")"	,GY)
HELP_URL("]"	,GY)
HELP_URL("⍣"		,SY"/star-diaeresis")

HELP_URL("⊆"	 , SY"/left-shoe-underbar")
HELP_URL("⎕U2286", SY"/left-shoe-underbar")

HELP_URL("⌸", SY"/quad-equal")
HELP_URL("⎕U2338", SY"/quad-equal")

HELP_URL("⌺", SY"/quad-diamond")
HELP_URL("⎕U233A", SY"/quad-diamond")

HELP_URL("⍛", SY"/jot-underbar")
HELP_URL("⎕U235B", SY"/jot-underbar")

HELP_URL("⍠", SY"/quad-colon")
HELP_URL("⎕OPT", SY"/quad-colon")
HELP_URL("⎕U2360", SY"/quad-colon")

HELP_URL("⍤", SY"/jot-diaeresis")
HELP_URL("⎕U2364", SY"/jot-diaeresis")

HELP_URL("⍥", SY"/circle-diaeresis")
HELP_URL("⎕U2365", SY"/circle-diaeresis")

HELP_URL("⍸", SY"/iota-underbar")
HELP_URL("⎕U2378", SY"/iota-underbar")


// System Commands

HELP_URL(")CLEAR"	,SYS"/clear")
HELP_URL(")CMD"		,SYS"/cmd")
HELP_URL(")CONTINUE"	,SYS"/continue")
HELP_URL(")COPY"	,SYS"/copy")
HELP_URL(")CS"		,SYS"/cs")
HELP_URL(")DROP"	,SYS"/drop")
HELP_URL(")ED"		,SYS"/ed")
HELP_URL(")ERASE"	,SYS"/erase")
HELP_URL(")EVENTS"	,SYS"/events")
HELP_URL(")FNS"		,SYS"/fns")
HELP_URL(")LIB"		,SYS"/lib")
HELP_URL(")LOAD"	,SYS"/load")
HELP_URL(")METHODS"	,SYS"/methods")
HELP_URL(")NS"		,SYS"/ns")
HELP_URL(")OBS"		,SYS"/obs")
HELP_URL(")OBJECTS"	,SYS"/objects")
HELP_URL(")OFF"		,SYS"/off")
HELP_URL(")OPS"		,SYS"/ops")
HELP_URL(")PCOPY"	,SYS"/pcopy")
HELP_URL(")PROPS"	,SYS"/props")
HELP_URL(")RESET"	,SYS"/reset")
HELP_URL(")SAVE"	,SYS"/save")
HELP_URL(")SH"		,SYS"/sh")
HELP_URL(")SI"		,SYS"/si")
HELP_URL(")SINL"	,SYS"/sinl")
HELP_URL(")HOLDS"	,SYS"/holds")
HELP_URL(")TID"		,SYS"/tid")
HELP_URL(")VARS"	,SYS"/vars")
HELP_URL(")WSID"	,SYS"/wsid")
HELP_URL(")XLOAD"	,SYS"/xload")
HELP_URL(")CLASSES"	,SYS"/classes")
HELP_URL(")SIC"		,SYS"/sic")


// System Functions
//
HELP_URL("⎕"	,"language-reference-guide/system-functions/evaluated-input-output")
HELP_URL("⍞"	,"language-reference-guide/system-functions/character-input-output")


HELP_URL("⎕A"		,QUAD"/a")
HELP_URL("⎕AI"		,QUAD"/ai")
HELP_URL("⎕AN"		,QUAD"/an")
HELP_URL("⎕AV"		,QUAD"/av")
HELP_URL("⎕CLEAR"	,QUAD"/clear")
HELP_URL("⎕D"		,QUAD"/d")
HELP_URL("⎕DM"		,QUAD"/dm")
HELP_URL("⎕EN"		,QUAD"/en")
HELP_URL("⎕EXCEPTION"	,QUAD"/exception")
HELP_URL("⎕FAVAIL"	,QUAD"/favail")
HELP_URL("⎕FNAMES"	,QUAD"/fnames")
HELP_URL("⎕FNUMS"	,QUAD"/fnums")
HELP_URL("⎕LC"		,QUAD"/lc")
HELP_URL("⎕NNAMES"	,QUAD"/nnames")
HELP_URL("⎕NNUMS"	,QUAD"/nnums")
HELP_URL("⎕NSI"		,QUAD"/nsi")
HELP_URL("⎕NULL"	,QUAD"/null")
HELP_URL("⎕OFF"		,QUAD"/off")
HELP_URL("⎕RSI"		,QUAD"/rsi")
HELP_URL("⎕SD"		,QUAD"/sd")
HELP_URL("⎕SI"		,QUAD"/si")
HELP_URL("⎕STACK"	,QUAD"/stack")
HELP_URL("⎕TC"		,QUAD"/tc")
HELP_URL("⎕TID"		,QUAD"/tid")
HELP_URL("⎕TNUMS"	,QUAD"/tnums")
HELP_URL("⎕TPOOL"	,QUAD"/tpool")
HELP_URL("⎕TS"		,QUAD"/ts")
HELP_URL("⎕WA"		,QUAD"/wa")
HELP_URL("⎕XSI"		,QUAD"/xsi")
HELP_URL("⎕Á"		,QUAD"/underscored-alphabetic-characters")
HELP_URL("⎕THIS"	,QUAD"/this")
HELP_URL("⎕BASE"	,QUAD"/base")
HELP_URL("⎕ARBIN"	,QUAD"/arbin")
HELP_URL("⎕ARBOUT"	,QUAD"/arbout")
HELP_URL("⎕AT"		,QUAD"/at")
HELP_URL("⎕ATX"		,QUAD"/atx")
HELP_URL("⎕CLASS"	,QUAD"/class")
HELP_URL("⎕CMD"		,QUAD"/cmd")
HELP_URL("⎕CR"		,QUAD"/cr")
HELP_URL("⎕CS"		,QUAD"/cs")
HELP_URL("⎕CSV"		,QUAD"/csv")
HELP_URL("⎕CY"		,QUAD"/cy")
HELP_URL("⎕DF"		,QUAD"/df")
HELP_URL("⎕DL"		,QUAD"/dl")
HELP_URL("⎕DQ"		,QUAD"/dq")
HELP_URL("⎕DR"		,QUAD"/dr")
HELP_URL("⎕ED"		,QUAD"/ed")
HELP_URL("⎕EM"		,QUAD"/em")
HELP_URL("⎕EX"		,QUAD"/ex")
HELP_URL("⎕EXPORT"	,QUAD"/export")
HELP_URL("⎕FAPPEND"	,QUAD"/fappend")
HELP_URL("⎕FCHK"	,QUAD"/fchk")
HELP_URL("⎕FCOPY"	,QUAD"/fcopy")
HELP_URL("⎕FCREATE"	,QUAD"/fcreate")
HELP_URL("⎕FDROP"	,QUAD"/fdrop")
HELP_URL("⎕FERASE"	,QUAD"/ferase")
HELP_URL("⎕FHOLD"	,QUAD"/fhold")
HELP_URL("⎕FIX"		,QUAD"/fix")
HELP_URL("⎕FLIB"	,QUAD"/flib")
HELP_URL("⎕FMT"		,QUAD"/fmt")
HELP_URL("⎕FPROPS"	,QUAD"/fprops")
HELP_URL("⎕FRDAC"	,QUAD"/frdac")
HELP_URL("⎕FRDCI"	,QUAD"/frdci")
HELP_URL("⎕FREAD"	,QUAD"/fread")
HELP_URL("⎕FRENAME"	,QUAD"/frename")
HELP_URL("⎕FREPLACE"	,QUAD"/freplace")
HELP_URL("⎕FRESIZE"	,QUAD"/fresize")
HELP_URL("⎕FSIZE"	,QUAD"/fsize")
HELP_URL("⎕FSTAC"	,QUAD"/fstac")
HELP_URL("⎕FSTIE"	,QUAD"/fstie")
HELP_URL("⎕FTIE"	,QUAD"/ftie")
HELP_URL("⎕FUNTIE"	,QUAD"/funtie")
HELP_URL("⎕FX"		,QUAD"/fx")
HELP_URL("⎕INSTANCES"	,QUAD"/instances")
HELP_URL("⎕JSON"	,QUAD"/json")
HELP_URL("⎕KL"		,QUAD"/kl")
HELP_URL("⎕LOAD"	,QUAD"/load")
HELP_URL("⎕LOCK"	,QUAD"/lock")
HELP_URL("⎕MKDIR"	,QUAD"/mkdir")
HELP_URL("⎕MONITOR"	,QUAD"/monitor")
HELP_URL("⎕NA"		,QUAD"/na")
HELP_URL("⎕NAPPEND"	,QUAD"/nappend")
HELP_URL("⎕NC"		,QUAD"/nc")
HELP_URL("⎕NCOPY"	,QUAD"/ncopy")
HELP_URL("⎕NCREATE"	,QUAD"/ncreate")
HELP_URL("⎕NDELETE"	,QUAD"/ndelete")
HELP_URL("⎕NERASE"	,QUAD"/nerase")
HELP_URL("⎕NEXISTS"	,QUAD"/nexists")
HELP_URL("⎕NGET"	,QUAD"/nget")
HELP_URL("⎕NINFO"	,QUAD"/ninfo")
HELP_URL("⎕NL"		,QUAD"/nl")
HELP_URL("⎕NLOCK"	,QUAD"/nlock")
HELP_URL("⎕NMOVE"	,QUAD"/nmove")
HELP_URL("⎕NPARTS"	,QUAD"/nparts")
HELP_URL("⎕NPUT"	,QUAD"/nput")
HELP_URL("⎕NQ"		,QUAD"/nq")
HELP_URL("⎕NR"		,QUAD"/nr")
HELP_URL("⎕NREAD"	,QUAD"/nread")
HELP_URL("⎕NRENAME"	,QUAD"/nrename")
HELP_URL("⎕NREPLACE"	,QUAD"/nreplace")
HELP_URL("⎕NRESIZE"	,QUAD"/nresize")
HELP_URL("⎕NS"		,QUAD"/ns")
HELP_URL("⎕NSIZE"	,QUAD"/nsize")
HELP_URL("⎕NTIE"	,QUAD"/ntie")
HELP_URL("⎕NUNTIE"	,QUAD"/nuntie")
HELP_URL("⎕NXLATE"	,QUAD"/nxlate")
HELP_URL("⎕MAP"		,QUAD"/map")
HELP_URL("⎕NEW"		,QUAD"/new")
HELP_URL("⎕OR"		,QUAD"/or")
HELP_URL("⎕PFKEY"	,QUAD"/pfkey")
HELP_URL("⎕PROFILE"	,QUAD"/profile")
HELP_URL("⎕FHIST"	,QUAD"/fhist")
HELP_URL("⎕REFS"	,QUAD"/refs")
HELP_URL("⎕SAVE"	,QUAD"/save")
HELP_URL("⎕SH"		,QUAD"/sh")
HELP_URL("⎕SHELL"	,QUAD"/shell")
HELP_URL("⎕SHADOW"	,QUAD"/shadow")
HELP_URL("⎕SHELL"	,QUAD"/shell")
HELP_URL("⎕SIGNAL"	,QUAD"/signal")
HELP_URL("⎕SIZE"	,QUAD"/size")
HELP_URL("⎕SR"		,QUAD"/sr")
HELP_URL("⎕SRC"		,QUAD"/src")
HELP_URL("⎕STATE"	,QUAD"/state")
HELP_URL("⎕STOP"	,QUAD"/stop")
HELP_URL("⎕SVC"		,QUAD"/svc")
HELP_URL("⎕SVO"		,QUAD"/svo")
HELP_URL("⎕SVQ"		,QUAD"/svq")
HELP_URL("⎕SVR"		,QUAD"/svr")
HELP_URL("⎕SVS"		,QUAD"/svs")
HELP_URL("⎕TALLOC"	,QUAD"/talloc")
HELP_URL("⎕TKILL"	,QUAD"/tkill")
HELP_URL("⎕TCNUMS"	,QUAD"/tcnums")
HELP_URL("⎕TSYNC"	,QUAD"/tsync")
HELP_URL("⎕TRACE"	,QUAD"/trace")
HELP_URL("⎕TGET"	,QUAD"/tget")
HELP_URL("⎕TPUT"	,QUAD"/tput")
HELP_URL("⎕TREQ"	,QUAD"/treq")
HELP_URL("⎕UCS"		,QUAD"/ucs")
HELP_URL("⎕VFI"		,QUAD"/vfi")
HELP_URL("⎕VGET"	,QUAD"/vget")
HELP_URL("⎕VR"		,QUAD"/vr")
HELP_URL("⎕VSET"	,QUAD"/vset")
HELP_URL("⎕WC"		,QUAD"/wc")
HELP_URL("⎕WG"		,QUAD"/wg")
HELP_URL("⎕WN"		,QUAD"/wn")
HELP_URL("⎕WS"		,QUAD"/ws")
HELP_URL("⎕XML"		,QUAD"/xml")
HELP_URL("⎕XT"		,QUAD"/xt")
HELP_URL("⎕DT"		,QUAD"/dt")
HELP_URL("⎕C"		,QUAD"/c")
HELP_URL("⎕R"		,QUAD"/r")
HELP_URL("⎕S"		,QUAD"/s")


HELP_URL("⎕PW",QUAD"/pw")
HELP_URL("⎕SE",QUAD"/se")
HELP_URL("⎕PATH",QUAD"/path")
HELP_URL("⎕LX",QUAD"/lx")
HELP_URL("⎕SM",QUAD"/sm")
HELP_URL("⎕TRAP",QUAD"/trap")
HELP_URL("⎕WSID",QUAD"/wsid")
HELP_URL("⎕TNAME",QUAD"/tname")
HELP_URL("⎕DMX",QUAD"/dmx")
HELP_URL("⎕CT",QUAD"/ct")
HELP_URL("⎕DIV",QUAD"/div")
HELP_URL("⎕IO",QUAD"/io")
HELP_URL("⎕ML",QUAD"/ml")
HELP_URL("⎕PP",QUAD"/pp")
HELP_URL("⎕RL",QUAD"/rl")
HELP_URL("⎕RTL",QUAD"/rtl")
HELP_URL("⎕WX",QUAD"/wx")
HELP_URL("⎕USING",QUAD"/using")
HELP_URL("⎕AVU",QUAD"/avu")
HELP_URL("⎕DCT",QUAD"/dct")
HELP_URL("⎕FR",QUAD"/fr")


// objects

HELP_URL("Root",OBJ"/root")
HELP_URL("Form",OBJ"/form")
HELP_URL("Button",OBJ"/button")
HELP_URL("Static",OBJ"/static")
HELP_URL("Edit",OBJ"/edit")
HELP_URL("Label",OBJ"/label")
HELP_URL("MenuBar",OBJ"/menubar")
HELP_URL("Menu",OBJ"/menu")
HELP_URL("MenuItem",OBJ"/menuitem")
HELP_URL("Separator",OBJ"/separator")
HELP_URL("List",OBJ"/list")
HELP_URL("Group",OBJ"/group")
HELP_URL("Scroll",OBJ"/scroll")
HELP_URL("Combo",OBJ"/combo")
HELP_URL("SM",OBJ"/sm")
HELP_URL("MsgBox",OBJ"/msgbox")
HELP_URL("Font",OBJ"/font")
HELP_URL("FileBox",OBJ"/filebox")
HELP_URL("Poly",OBJ"/poly")
HELP_URL("Ellipse",OBJ"/ellipse")
HELP_URL("Circle",OBJ"/circle")
HELP_URL("Text",OBJ"/text")
HELP_URL("Rect",OBJ"/rect")
HELP_URL("Marker",OBJ"/marker")
HELP_URL("Printer",OBJ"/printer")
HELP_URL("Bitmap",OBJ"/bitmap")
HELP_URL("Icon",OBJ"/icon")
HELP_URL("Cursor",OBJ"/cursor")
HELP_URL("Image",OBJ"/image")
HELP_URL("Clipboard",OBJ"/clipboard")
HELP_URL("Locator",OBJ"/locator")
HELP_URL("Timer",OBJ"/timer")
HELP_URL("Metafile",OBJ"/metafile")
//HELP_URL("Clip",OBJ"/Clip")
HELP_URL("MDIClient",OBJ"/mdiclient")
HELP_URL("ToolBar",OBJ"/toolbar")
HELP_URL("StatusBar",OBJ"/statusbar")
HELP_URL("StatusField",OBJ"/statusfield")
HELP_URL("TipField",OBJ"/tipfield")
HELP_URL("TabBtn",OBJ"/tabbtn")
HELP_URL("TabBar",OBJ"/tabbar")
HELP_URL("Grid",OBJ"/grid")
HELP_URL("SubForm",OBJ"/subform")
HELP_URL("TrackBar",OBJ"/trackbar")
HELP_URL("RichEdit",OBJ"/richedit")
HELP_URL("ProgressBar",OBJ"/progressbar")
HELP_URL("TreeView",OBJ"/treeview")
HELP_URL("ListView",OBJ"/listview")
HELP_URL("UpDown",OBJ"/updown")
HELP_URL("ImageList",OBJ"/imagelist")
HELP_URL("PropertySheet",OBJ"/propertysheet")
HELP_URL("PropertyPage",OBJ"/propertypage")
HELP_URL("Spinner",OBJ"/spinner")
HELP_URL("OCXClass",OBJ"/ocxclass")
HELP_URL("OLEServer",OBJ"/oleserver")
HELP_URL("OLEClient",OBJ"/oleclient")
#if 0
HELP_URL("Class",OBJ"/class")
HELP_URL("Session",OBJ"/session")
HELP_URL("NameSpace",OBJ"/namespace")
HELP_URL("DragList",OBJ"/draglist")
HELP_URL("MMControl",OBJ"/mmcontrol")
HELP_URL("OCXControl",OBJ"/ocxcontrol")
HELP_URL("VBXControl",OBJ"/vbxcontrol")
HELP_URL("Interface",OBJ"/interface")
HELP_URL("ColorPicker",OBJ"/colorpicker")	// is this a thing?
HELP_URL("HotKeyControl",OBJ"/hotkeycontrol")
HELP_URL("SessionStatus",OBJ"/sessionstatus")
HELP_URL("SessionEditor",OBJ"/sessioneditor")
HELP_URL("SessionScriptCompiler",OBJ"/sessionscriptcompiler")
HELP_URL("FileWatcher",OBJ"/filewatcher")
#endif
HELP_URL("TCPSocket",OBJ"/tcpsocket")
HELP_URL("Splitter",OBJ"/splitter")
HELP_URL("CoolBar",OBJ"/coolbar")
HELP_URL("ToolControl",OBJ"/toolcontrol")
HELP_URL("ToolButton",OBJ"/toolbutton")
HELP_URL("SysTrayItem",OBJ"/systrayitem")
HELP_URL("TabControl",OBJ"/tabcontrol")
HELP_URL("TabButton",OBJ"/tabbutton")
HELP_URL("ColorButton",OBJ"/colorbutton")
HELP_URL("ActiveXContainer",OBJ"/activexcontainer")
HELP_URL("ActiveXControl",OBJ"/activexcontrol")
HELP_URL("CoolBand",OBJ"/coolband")
HELP_URL("Calendar",OBJ"/calendar")
HELP_URL("DateTimePicker",OBJ"/datetimepicker")
HELP_URL("ComboEx",OBJ"/comboex")
HELP_URL("BrowseBox",OBJ"/browsebox")
HELP_URL("Animation",OBJ"/animation")
HELP_URL("NetClient",OBJ"/netclient")
HELP_URL("NetType",OBJ"/nettype")
HELP_URL("NetControl",OBJ"/netcontrol")
HELP_URL("ButtonEdit",OBJ"/buttonedit")
HELP_URL("HTMLRenderer",OBJ"/htmlrenderer")

// methods or events

//HELP_URL("All",EVENT"/All")		// is this/should this be documented
HELP_URL("MouseDown",EVENT"/mousedown")
HELP_URL("MouseUp",EVENT"/mouseup")
HELP_URL("MouseMove",EVENT"/mousemove")
//HELP_URL("MouseClick",EVENT"/MouseClick")
HELP_URL("MouseDblClick",EVENT"/mousedblclick")
HELP_URL("MouseEnter",EVENT"/mouseenter")
HELP_URL("MouseLeave",EVENT"/mouseleave")
HELP_URL("MouseWheel",EVENT"/mousewheel")
#if 0
HELP_URL("DragOver",EVENT"/dragover")
HELP_URL("DragDrop",EVENT"/dragdrop")
HELP_URL("DragStart",EVENT"/dragstart")
HELP_URL("DragListMove",EVENT"/draglistmove")
HELP_URL("DragListCopy",EVENT"/draglistcopy")
HELP_URL("KeyChar",EVENT"/keychar")
HELP_URL("KeyDown",EVENT"/keydown")
HELP_URL("KeyUp",EVENT"/keyup")
#endif
HELP_URL("KeyPress",EVENT"/keypress")
HELP_URL("KeyError",EVENT"/keyerror")
HELP_URL("GridKeyPress",EVENT"/gridkeypress")
HELP_URL("ShowSIP",EVENT"/showsip")
HELP_URL("Animate",EVENT"/animate")
HELP_URL("Select",EVENT"/select")
HELP_URL("Configure",EVENT"/configure")
HELP_URL("Expose",EVENT"/expose")
HELP_URL("Close",EVENT"/close")
HELP_URL("Create",EVENT"/create")
HELP_URL("StateChange",EVENT"/statechange")
HELP_URL("Change",EVENT"/change")
HELP_URL("Scroll",EVENT"/scroll")
HELP_URL("VScroll",EVENT"/vscroll")
HELP_URL("HScroll",EVENT"/hscroll")
HELP_URL("GotFocus",EVENT"/gotfocus")
HELP_URL("LostFocus",EVENT"/lostfocus")
HELP_URL("MDIActivate",EVENT"/mdiactivate")
HELP_URL("MDIDeactivate",EVENT"/mdideactivate")
HELP_URL("DropDown",EVENT"/dropdown")
HELP_URL("CloseUp",EVENT"/closeup")
HELP_URL("DDE",EVENT"/dde")
HELP_URL("MsgBtn1",EVENT"/msgbtn1")
HELP_URL("MsgBtn2",EVENT"/msgbtn2")
HELP_URL("MsgBtn3",EVENT"/msgbtn3")
HELP_URL("FileBoxOK",EVENT"/fileboxok")
HELP_URL("FileBoxCancel",EVENT"/fileboxcancel")
HELP_URL("Locator",EVENT"/locator")
HELP_URL("FileRead",EVENT"/fileread")
HELP_URL("FileWrite",EVENT"/filewrite")
HELP_URL("GetServiceState",EVENT"/getservicestate")
HELP_URL("SetServiceState",EVENT"/setservicestate")
HELP_URL("ServiceNotification",EVENT"/servicenotification")
HELP_URL("DyalogCustomMessage1",EVENT"/dyalogcustommessage1")
HELP_URL("Print",EVENT"/print")
HELP_URL("Setup",EVENT"/setup")
HELP_URL("NewPage",EVENT"/newpage")
HELP_URL("Abort",EVENT"/abort")
HELP_URL("MDICascade",EVENT"/mdicascade")
HELP_URL("MDITile",EVENT"/mditile")
HELP_URL("MDIArrange",EVENT"/mdiarrange")
HELP_URL("ClipChange",EVENT"/clipchange")
//HELP_URL("ObjectFromHandle",EVENT"/ObjectFromHandle")
HELP_URL("Idle",EVENT"/idle")
HELP_URL("ExitWindows",EVENT"/exitwindows")
HELP_URL("ExitApp",EVENT"/exitapp")
HELP_URL("WinIniChange",EVENT"/wininichange")
HELP_URL("SysColorChange",EVENT"/syscolorchange")
HELP_URL("Flush",EVENT"/flush")
HELP_URL("NameFromHandle",EVENT"/namefromhandle")
HELP_URL("DisplayChange",EVENT"/displaychange")
HELP_URL("GreetBitmap",EVENT"/greetbitmap")
HELP_URL("ActivateApp",EVENT"/activateapp")
HELP_URL("Timer",EVENT"/timer")
//HELP_URL("SetUnicodeTable",EVENT"/SetUnicodeTable")
HELP_URL("GetCommandLine",EVENT"/getcommandline")
HELP_URL("GetTextSize",EVENT"/gettextsize")
HELP_URL("Wait",EVENT"/wait")
HELP_URL("GetCommandLineArgs",EVENT"/getcommandlineargs")
//HELP_URL("ReadUnicodeFile",EVENT"/ReadUnicodeFile")
HELP_URL("CellChange",EVENT"/cellchange")
HELP_URL("CellMove",EVENT"/cellmove")
HELP_URL("AddRow",EVENT"/addrow")
HELP_URL("AddCol",EVENT"/addcol")
HELP_URL("DelRow",EVENT"/delrow")
HELP_URL("DelCol",EVENT"/delcol")
HELP_URL("SetCellType",EVENT"/setcelltype")
HELP_URL("CellError",EVENT"/cellerror")
HELP_URL("RowChange",EVENT"/rowchange")
HELP_URL("ColChange",EVENT"/colchange")
HELP_URL("CellOver",EVENT"/cellover")
HELP_URL("CellDown",EVENT"/celldown")
HELP_URL("CellUp",EVENT"/cellup")
HELP_URL("CellDblClick",EVENT"/celldblclick")
HELP_URL("CellChanged",EVENT"/cellchanged")
HELP_URL("GridSelect",EVENT"/gridselect")
HELP_URL("Undo",EVENT"/undo")
HELP_URL("SetCellSet",EVENT"/setcellset")
HELP_URL("RowSetVisibleDepth",EVENT"/rowsetvisibledepth")
HELP_URL("ColSorted",EVENT"/colsorted")
HELP_URL("SetRowSize",EVENT"/setrowsize")
HELP_URL("SetColSize",EVENT"/setcolsize")
HELP_URL("DuplicateRow",EVENT"/duplicaterow")
HELP_URL("DuplicateColumn",EVENT"/duplicatecolumn")
HELP_URL("BadValue",EVENT"/badvalue")
HELP_URL("GridCut",EVENT"/gridcut")
HELP_URL("GridCopy",EVENT"/gridcopy")
HELP_URL("GridPaste",EVENT"/gridpaste")
HELP_URL("GridDelete",EVENT"/griddelete")
HELP_URL("GridPasteError",EVENT"/gridpasteerror")
HELP_URL("GridDropSel",EVENT"/griddropsel")
HELP_URL("GridCopyError",EVENT"/gridcopyerror")
HELP_URL("CellFromPoint",EVENT"/cellfrompoint")
HELP_URL("GetCellRect",EVENT"/getcellrect")
HELP_URL("IndexChanged",EVENT"/indexchanged")
HELP_URL("AddComment",EVENT"/addcomment")
HELP_URL("DelComment",EVENT"/delcomment")
HELP_URL("GetComment",EVENT"/getcomment")
HELP_URL("ShowComment",EVENT"/showcomment")
HELP_URL("HideComment",EVENT"/hidecomment")
HELP_URL("ClickComment",EVENT"/clickcomment")
HELP_URL("LockRows",EVENT"/lockrows")
HELP_URL("LockColumns",EVENT"/lockcolumns")
#if 0
HELP_URL("HideRows",EVENT"/hiderows")
HELP_URL("HideColumns",EVENT"/hidecolumns")
HELP_URL("ProtectRows",EVENT"/protectrows")
HELP_URL("ProtectColumns",EVENT"/protectcolumns")
#endif
HELP_URL("ChooseFont",EVENT"/choosefont")
HELP_URL("FontOK",EVENT"/fontok")
HELP_URL("FontCancel",EVENT"/fontcancel")
HELP_URL("ProgressStep",EVENT"/progressstep")
HELP_URL("MakePNG",EVENT"/makepng")
HELP_URL("MakeGIF",EVENT"/makegif")
HELP_URL("GetVisibleRange",EVENT"/getvisiblerange")
HELP_URL("IDNToDate",EVENT"/idntodate")
HELP_URL("DateToIDN",EVENT"/datetoidn")
HELP_URL("SelDateChange",EVENT"/seldatechange")
HELP_URL("GetDayStates",EVENT"/getdaystates")
HELP_URL("DateTimeChange",EVENT"/datetimechange")
HELP_URL("Detach",EVENT"/detach")
HELP_URL("CalendarDown",EVENT"/calendardown")
HELP_URL("CalendarUp",EVENT"/calendarup")
HELP_URL("CalendarDblClick",EVENT"/calendardblclick")
HELP_URL("CalendarMove",EVENT"/calendarmove")
HELP_URL("GetMinSize",EVENT"/getminsize")
HELP_URL("StartSplit",EVENT"/startsplit")
HELP_URL("Splitting",EVENT"/splitting")
HELP_URL("EndSplit",EVENT"/endsplit")
HELP_URL("AnimOpen",EVENT"/animopen")
HELP_URL("AnimClose",EVENT"/animclose")
HELP_URL("AnimPlay",EVENT"/animplay")
HELP_URL("AnimStop",EVENT"/animstop")
HELP_URL("AnimStarted",EVENT"/animstarted")
HELP_URL("AnimStopped",EVENT"/animstopped")
HELP_URL("BeginEditLabel",EVENT"/begineditlabel")
HELP_URL("EndEditLabel",EVENT"/endeditlabel")
HELP_URL("Expanding",EVENT"/expanding")
//HELP_URL("Expanded",EVENT"/Expanded")
HELP_URL("Retracting",EVENT"/retracting")
//HELP_URL("Retracted",EVENT"/Retracted")
HELP_URL("GetItemState",EVENT"/getitemstate")
HELP_URL("SetItemState",EVENT"/setitemstate")
HELP_URL("AddItems",EVENT"/additems")
HELP_URL("DeleteItems",EVENT"/deleteitems")
HELP_URL("AddChildren",EVENT"/addchildren")
HELP_URL("DeleteChildren",EVENT"/deletechildren")
HELP_URL("GetParentItem",EVENT"/getparentitem")
HELP_URL("GetItemHandle",EVENT"/getitemhandle")
HELP_URL("SetItemImage",EVENT"/setitemimage")
HELP_URL("ShowItem",EVENT"/showitem")
HELP_URL("ColumnClick",EVENT"/columnclick")
//HELP_URL("ColumnDblClick",EVENT"/ColumnDblClick")
HELP_URL("SetItemPosition",EVENT"/setitemposition")
HELP_URL("GetItemPosition",EVENT"/getitemposition")
//HELP_URL("Update",EVENT"/Update")
HELP_URL("GetTipText",EVENT"/gettiptext")
HELP_URL("ItemDown",EVENT"/itemdown")
HELP_URL("ItemUp",EVENT"/itemup")
HELP_URL("ItemDblClick",EVENT"/itemdblclick")
HELP_URL("PageApply",EVENT"/pageapply")
HELP_URL("PageCancel",EVENT"/pagecancel")
HELP_URL("PageHelp",EVENT"/pagehelp")
HELP_URL("PageBack",EVENT"/pageback")
HELP_URL("PageNext",EVENT"/pagenext")
HELP_URL("PageFinish",EVENT"/pagefinish")
HELP_URL("PageChanged",EVENT"/pagechanged")
//HELP_URL("ApplyEnable",EVENT"/ApplyEnable")
HELP_URL("PageActivate",EVENT"/pageactivate")
HELP_URL("PageDeactivate",EVENT"/pagedeactivate")
HELP_URL("SetWizard",EVENT"/setwizard")
HELP_URL("SetFinishText",EVENT"/setfinishtext")
HELP_URL("CancelToClose",EVENT"/canceltoclose")
HELP_URL("TCPError",EVENT"/tcperror")
HELP_URL("TCPAccept",EVENT"/tcpaccept")
HELP_URL("TCPConnect",EVENT"/tcpconnect")
HELP_URL("TCPRecv",EVENT"/tcprecv")
HELP_URL("TCPClose",EVENT"/tcpclose")
HELP_URL("TCPSend",EVENT"/tcpsend")
HELP_URL("TCPGetHostID",EVENT"/tcpgethostid")
HELP_URL("TCPGotAddr",EVENT"/tcpgotaddr")
HELP_URL("TCPGotPort",EVENT"/tcpgotport")
HELP_URL("TCPReady",EVENT"/tcpready")
HELP_URL("TCPSendPicture",EVENT"/tcpsendpicture")
#if 0
HELP_URL("MMOpen",EVENT"/mmopen")
HELP_URL("MMClose",EVENT"/mmclose")
HELP_URL("MMPlay",EVENT"/mmplay")
HELP_URL("MMStop",EVENT"/mmstop")
HELP_URL("MMReverse",EVENT"/mmreverse")
HELP_URL("GetMMError",EVENT"/getmmerror")
HELP_URL("MMError",EVENT"/mmerror")
HELP_URL("MMMediaChanged",EVENT"/mmmediachanged")
HELP_URL("MMModeChanged",EVENT"/mmmodechanged")
HELP_URL("MMPosChanged",EVENT"/mmposchanged")
HELP_URL("Help",EVENT"/help")
HELP_URL("MMSizeChanged",EVENT"/mmsizechanged")
HELP_URL("MMOpenDialog",EVENT"/mmopendialog")
HELP_URL("MMEject",EVENT"/mmeject")

HELP_URL("MMCurPos",PROP"/mmcurpos")
HELP_URL("MMCurPosString",PROP"/mmcurposstring")
HELP_URL("MMCurMode",PROP"/mmcurmode")

HELP_URL("SendString",EVENT"/sendstring")
HELP_URL("ReceiveString",EVENT"/receivestring")

#endif

HELP_URL("ContextMenu",EVENT"/contextmenu")
HELP_URL("FrameContextMenu",EVENT"/framecontextmenu")
HELP_URL("Spin",EVENT"/spin")
HELP_URL("SetSpinnerText",EVENT"/setspinnertext")
HELP_URL("ColorChange",EVENT"/colorchange")
HELP_URL("ThumbDrag",EVENT"/thumbdrag")
HELP_URL("VThumbDrag",EVENT"/vthumbdrag")
HELP_URL("HThumbDrag",EVENT"/hthumbdrag")
HELP_URL("DropFiles",EVENT"/dropfiles")
HELP_URL("DropObjects",EVENT"/dropobjects")
HELP_URL("RTFPrintSetup",EVENT"/rtfprintsetup")
HELP_URL("RTFPrint",EVENT"/rtfprint")
HELP_URL("Protected",EVENT"/protected")
HELP_URL("DockStart",EVENT"/dockstart")
HELP_URL("DockMove",EVENT"/dockmove")
HELP_URL("DockRequest",EVENT"/dockrequest")
HELP_URL("DockAccept",EVENT"/dockaccept")
HELP_URL("DockEnd",EVENT"/dockend")
HELP_URL("DockCancel",EVENT"/dockcancel")
#if 0
HELP_URL("Gesture",EVENT"/gesture")
HELP_URL("GestureBegin",EVENT"/gesturebegin")
HELP_URL("GestureEnd",EVENT"/gestureend")
#endif
HELP_URL("GestureZoom",EVENT"/gesturezoom")
HELP_URL("GesturePan",EVENT"/gesturepan")
HELP_URL("GestureRotate",EVENT"/gesturerotate")
HELP_URL("GestureTwoFingerTap",EVENT"/gesturetwofingertap")
HELP_URL("GesturePressAndTap",EVENT"/gesturepressandtap")
#if 0
HELP_URL("VBXRefresh",EVENT"/vbxrefresh")
HELP_URL("VBXMove",EVENT"/vbxmove")
HELP_URL("VBXAddItem",EVENT"/vbxadditem")
HELP_URL("VBXRemove",EVENT"/vbxremove")
#endif
HELP_URL("GetFocusObj",EVENT"/getfocusobj")
HELP_URL("GetEnvironment",EVENT"/getenvironment")
HELP_URL("GetFocus",EVENT"/getfocus")
//HELP_URL("Aplmon",EVENT"/Aplmon")
HELP_URL("ListTypeLibs",EVENT"/listtypelibs")
HELP_URL("DeleteTypeLib",EVENT"/deletetypelib")
HELP_URL("WorkspaceLoaded",EVENT"/workspaceloaded")
HELP_URL("SessionPrint",EVENT"/sessionprint")
HELP_URL("OLERegister",EVENT"/oleregister")
HELP_URL("OLEUnregister",EVENT"/oleunregister")
//HELP_URL("OLEMakeOCX",EVENT"/OLEMakeOCX")
HELP_URL("AmbientChanged",EVENT"/ambientchanged")
HELP_URL("PreCreate",EVENT"/precreate")
HELP_URL("OLEAddEventSink",EVENT"/oleaddeventsink")
HELP_URL("OLEDeleteEventSink",EVENT"/oledeleteeventsink")
HELP_URL("OLEListEventSinks",EVENT"/olelisteventsinks")
HELP_URL("OLEQueryInterface",EVENT"/olequeryinterface")
HELP_URL("SetFnInfo",EVENT"/setfninfo")
HELP_URL("SetVarInfo",EVENT"/setvarinfo")
HELP_URL("SetEventInfo",EVENT"/seteventinfo")
HELP_URL("GetAllEvents",EVENT"/getallevents")
HELP_URL("GetPropertyInfo",EVENT"/getpropertyinfo")
HELP_URL("GetEventInfo",EVENT"/geteventinfo")
HELP_URL("GetMethodInfo",EVENT"/getmethodinfo")
HELP_URL("GetTypeInfo",EVENT"/gettypeinfo")
HELP_URL("SetPropertyInfo",EVENT"/setpropertyinfo")
HELP_URL("SetMethodInfo",EVENT"/setmethodinfo")
HELP_URL("ShowProperties",EVENT"/showproperties")
HELP_URL("ShowHelp",EVENT"/showhelp")
HELP_URL("Browse",EVENT"/browse")

#if 0
HELP_URL("ShowVerbMenu",EVENT"/showverbmenu")
HELP_URL("DeletePropertyInfo",EVENT"/deletepropertyinfo")
HELP_URL("DeleteEventInfo",EVENT"/deleteeventinfo")
HELP_URL("DeleteMethodInfo",EVENT"/deletemethodinfo")
HELP_URL("Bind",EVENT"/bind")
HELP_URL("BaseConstructor",EVENT"/baseconstructor")
HELP_URL("As",EVENT"/as")
#endif

#if 0
HELP_URL("SetFieldInfo",EVENT"/setfieldinfo")
HELP_URL("GetFieldInfo",EVENT"/getfieldinfo")
HELP_URL("Clear",EVENT"/clear")
HELP_URL("AddText",EVENT"/addtext")
HELP_URL("AddLine",EVENT"/addline")
#endif

HELP_URL("Fix",EVENT"/fix")
HELP_URL("Format",EVENT"/format")
HELP_URL("AfterFix",EVENT"/afterfix")
//HELP_URL("ScriptCompilerError",EVENT"/ScriptCompilerError")
HELP_URL("HTTPRequest",EVENT"/httprequest")
HELP_URL("WebSocketUpgrade",EVENT"/websocketupgrade")
HELP_URL("WebSocketReceive",EVENT"/websocketreceive")
HELP_URL("WebSocketClose",EVENT"/websocketclose")
HELP_URL("WebSocketError",EVENT"/websocketerror")
HELP_URL("PrintToPDF",EVENT"/printtopdf")
HELP_URL("DoPopup",EVENT"/dopopup")
HELP_URL("ExecuteJavaScript",EVENT"/executejavascript")
HELP_URL("WebSocketSend",EVENT"/websocketsend")
HELP_URL("SelectCertificate",EVENT"/selectcertificate")
HELP_URL("ShowDevTools",EVENT"/showdevtools")
#if 0
HELP_URL("SetInputEncoding",EVENT"/setinputencoding")
HELP_URL("SetOutputEncoding",EVENT"/setoutputencoding")
#endif
HELP_URL("ShowBalloonTip",EVENT"/showballoontip")
HELP_URL("BalloonShow",EVENT"/balloonshow")
HELP_URL("BalloonHide",EVENT"/balloonhide")
HELP_URL("BalloonTimeout",EVENT"/balloontimeout")
HELP_URL("BalloonUserClick",EVENT"/balloonuserclick")
//HELP_URL("FileChange",EVENT"/FileChange")
HELP_URL("GetBuildID",EVENT"/getbuildid")
#if 0
HELP_URL("wscheck",EVENT"/wscheck")
HELP_URL("SetDFlags",EVENT"/setdflags")
HELP_URL("DumpWS",EVENT"/dumpws")
HELP_URL("RefixWS",EVENT"/refixws")
HELP_URL("DumpWindows",EVENT"/dumpwindows")
HELP_URL("CoreDump",EVENT"/coredump")
HELP_URL("DockSessionItem",EVENT"/docksessionitem")
HELP_URL("CloseSessionItem",EVENT"/closesessionitem")
#endif

// properties

HELP_URL("Type",PROP"/type")
//HELP_URL("Path",PROP"/Path")
HELP_URL("Caption",PROP"/caption")
HELP_URL("SplitObj1",PROP"/splitobj1")           
HELP_URL("SplitObj2",PROP"/splitobj2")           
HELP_URL("HTML",PROP"/html")
HELP_URL("Values",PROP"/values")
HELP_URL("PName",PROP"/pname")
HELP_URL("BaseClass",PROP"/baseclass")
HELP_URL("ClassName",PROP"/classname")
#if 0
HELP_URL("ConstructorArgs",PROP"/constructorargs")
HELP_URL("Interfaces",PROP"/interfaces")
#endif
HELP_URL("Interval",PROP"/interval")
HELP_URL("FireOnce",PROP"/fireonce")
HELP_URL("Items",PROP"/items")
HELP_URL("Text",PROP"/text")
HELP_URL("Posn",PROP"/posn")
HELP_URL("Points",PROP"/points")
HELP_URL("Style",PROP"/style")
HELP_URL("Size",PROP"/size")
HELP_URL("URL",PROP"/url")
HELP_URL("CurrentColor",PROP"/currentcolor")
HELP_URL("DefaultColors",PROP"/defaultcolors")
HELP_URL("CustomColors",PROP"/customcolors")
HELP_URL("OtherButton",PROP"/otherbutton")
HELP_URL("Radius",PROP"/radius")
HELP_URL("FCol",PROP"/fcol")
HELP_URL("BCol",PROP"/bcol")
HELP_URL("Start",PROP"/start")
HELP_URL("End",PROP"/end")
HELP_URL("ArcMode",PROP"/arcmode")
HELP_URL("LStyle",PROP"/lstyle")
HELP_URL("LWidth",PROP"/lwidth")
HELP_URL("FStyle",PROP"/fstyle")
HELP_URL("FillCol",PROP"/fillcol")
HELP_URL("FBCol",PROP"/fbcol")
HELP_URL("DevCaps",PROP"/devcaps")
HELP_URL("VAlign",PROP"/valign")
HELP_URL("HAlign",PROP"/halign")
HELP_URL("Directory",PROP"/directory")
HELP_URL("BrowseFor",PROP"/browsefor")
HELP_URL("Target",PROP"/target")
HELP_URL("StartIn",PROP"/startin")
HELP_URL("HasEdit",PROP"/hasedit")
HELP_URL("Filters",PROP"/filters")
HELP_URL("File",PROP"/file")
HELP_URL("Bits",PROP"/bits")
HELP_URL("CMap",PROP"/cmap")
HELP_URL("Mask",PROP"/mask")
HELP_URL("HotSpot",PROP"/hotspot")
HELP_URL("FileMode",PROP"/filemode")
HELP_URL("Btns",PROP"/btns")
//HELP_URL("Port",PROP"/Port")
HELP_URL("KeepBits",PROP"/keepbits")
HELP_URL("Coord",PROP"/coord")
HELP_URL("RealSize",PROP"/realsize")
HELP_URL("Rows",PROP"/rows")
HELP_URL("Align",PROP"/align")
HELP_URL("Fixed",PROP"/fixed")
HELP_URL("State",PROP"/state")
HELP_URL("Default",PROP"/default")
HELP_URL("Cancel",PROP"/cancel")
HELP_URL("Border",PROP"/border")
HELP_URL("Justify",PROP"/justify")
HELP_URL("Active",PROP"/active")
HELP_URL("Visible",PROP"/visible")
//HELP_URL("Exclusive",PROP"/Exclusive")
HELP_URL("LocalAddr",PROP"/localaddr")
HELP_URL("LocalPort",PROP"/localport")
HELP_URL("RemoteAddr",PROP"/remoteaddr")
HELP_URL("RemotePort",PROP"/remoteport")
HELP_URL("Event",PROP"/event")
HELP_URL("AllEvents",PROP"/allevents")
HELP_URL("LocalAddrName",PROP"/localaddrname")
HELP_URL("LocalPortName",PROP"/localportname")
HELP_URL("RemoteAddrName",PROP"/remoteaddrname")
HELP_URL("RemotePortName",PROP"/remoteportname")
HELP_URL("DragItems",PROP"/dragitems")
HELP_URL("View",PROP"/view")
HELP_URL("AutoArrange",PROP"/autoarrange")
HELP_URL("Header",PROP"/header")
HELP_URL("Wrap",PROP"/wrap")
HELP_URL("Depth",PROP"/depth")
HELP_URL("Indents",PROP"/indents")
HELP_URL("HasLines",PROP"/haslines")
HELP_URL("HasButtons",PROP"/hasbuttons")
HELP_URL("EditLabels",PROP"/editlabels")
HELP_URL("ImageListObj",PROP"/imagelistobj")
HELP_URL("ReportInfo",PROP"/reportinfo")
HELP_URL("ColTitles",PROP"/coltitles")
HELP_URL("ImageIndex",PROP"/imageindex")
HELP_URL("SelImageIndex",PROP"/selimageindex")
HELP_URL("ReportImageList",PROP"/reportimagelist")
HELP_URL("ReportImageIndex",PROP"/reportimageindex")
HELP_URL("ReportBCol",PROP"/reportbcol")
HELP_URL("HeaderImageList",PROP"/headerimagelist")
HELP_URL("HeaderImageIndex",PROP"/headerimageindex")
HELP_URL("Wizard",PROP"/wizard")
HELP_URL("HasApply",PROP"/hasapply")
HELP_URL("HasHelp",PROP"/hashelp")
HELP_URL("PageActive",PROP"/pageactive")
HELP_URL("PageActiveObject",PROP"/pageactiveobject")

#if 0
HELP_URL("WaterMarkBitmap",PROP"/watermarkbitmap")
HELP_URL("HeaderBitmap",PROP"/headerbitmap")
HELP_URL("Stretch",PROP"/stretch")
HELP_URL("LastPage",PROP"/lastpage")
#endif

HELP_URL("CaseSensitive",PROP"/casesensitive")
HELP_URL("EditImage",PROP"/editimage")
HELP_URL("EditImageIndent",PROP"/editimageindent")
HELP_URL("PathWordBreak",PROP"/pathwordbreak")
HELP_URL("FirstDay",PROP"/firstday")
HELP_URL("MaxSelCount",PROP"/maxselcount")
HELP_URL("SelDate",PROP"/seldate")
HELP_URL("DateTime",PROP"/datetime")
HELP_URL("MinDate",PROP"/mindate")
HELP_URL("MaxDate",PROP"/maxdate")
HELP_URL("CalendarCols",PROP"/calendarcols")
HELP_URL("Today",PROP"/today")
HELP_URL("HasToday",PROP"/hastoday")
HELP_URL("CircleToday",PROP"/circletoday")
HELP_URL("WeekNumbers",PROP"/weeknumbers")
HELP_URL("MonthDelta",PROP"/monthdelta")
HELP_URL("HasCheckBox",PROP"/hascheckbox")
HELP_URL("FieldType",PROP"/fieldtype")
HELP_URL("CustomFormat",PROP"/customformat")
HELP_URL("Thumb",PROP"/thumb")
HELP_URL("Range",PROP"/range")
HELP_URL("Step",PROP"/step")
HELP_URL("VScroll",PROP"/vscroll")
HELP_URL("HScroll",PROP"/hscroll")
HELP_URL("Limits",PROP"/limits")
HELP_URL("SelItems",PROP"/selitems")
HELP_URL("SelText",PROP"/seltext")
HELP_URL("SelRange",PROP"/selrange")
HELP_URL("Sizeable",PROP"/sizeable")
HELP_URL("Moveable",PROP"/moveable")
HELP_URL("SysMenu",PROP"/sysmenu")
HELP_URL("MaxButton",PROP"/maxbutton")
HELP_URL("MinButton",PROP"/minbutton")
HELP_URL("HelpButton",PROP"/helpbutton")
HELP_URL("OKButton",PROP"/okbutton")
HELP_URL("SIPMode",PROP"/sipmode")
HELP_URL("SIPResize",PROP"/sipresize")
HELP_URL("Checked",PROP"/checked")
HELP_URL("Dragable",PROP"/dragable")
HELP_URL("FontObj",PROP"/fontobj")
HELP_URL("FontList",PROP"/fontlist")
HELP_URL("PrintList",PROP"/printlist")
HELP_URL("Height",PROP"/height")
HELP_URL("Italic",PROP"/italic")
HELP_URL("Underline",PROP"/underline")
HELP_URL("Weight",PROP"/weight")
HELP_URL("Rotate",PROP"/rotate")
HELP_URL("CharSet",PROP"/charset")
//HELP_URL("Bitmap",PROP"/Bitmap")
HELP_URL("Picture",PROP"/picture")
HELP_URL("OnTop",PROP"/ontop")
HELP_URL("BtnPix",PROP"/btnpix")
HELP_URL("IconObj",PROP"/iconobj")
HELP_URL("CursorObj",PROP"/cursorobj")
HELP_URL("AutoConf",PROP"/autoconf")
HELP_URL("Index",PROP"/index-property")
HELP_URL("YRange",PROP"/yrange")
HELP_URL("XRange",PROP"/xrange")
HELP_URL("EndPos",PROP"/endpos")
HELP_URL("Data",PROP"/data")
HELP_URL("Attach",PROP"/attach")
HELP_URL("Formats",PROP"/formats")
HELP_URL("CBits",PROP"/cbits")
HELP_URL("MetafileObj",PROP"/metafileobj")
HELP_URL("Array",PROP"/array")
HELP_URL("TextSize",PROP"/textsize")
HELP_URL("Yield",PROP"/yield")
HELP_URL("EdgeStyle",PROP"/edgestyle")
HELP_URL("MDIMenu",PROP"/mdimenu")
#if 0
HELP_URL("ClipObj",PROP"/clipobj")
HELP_URL("ClipMode",PROP"/clipmode")
#endif
HELP_URL("Handle",PROP"/handle")
HELP_URL("Orientation",PROP"/orientation")
HELP_URL("Copies",PROP"/copies")
HELP_URL("PrintRange",PROP"/printrange")
HELP_URL("Collate",PROP"/collate")
HELP_URL("PaperSize",PROP"/papersize")
HELP_URL("PaperSizes",PROP"/papersizes")
HELP_URL("PaperSource",PROP"/papersource")
HELP_URL("PaperSources",PROP"/papersources")
HELP_URL("ColorMode",PROP"/colormode")
HELP_URL("Resolution",PROP"/resolution")
HELP_URL("Resolutions",PROP"/resolutions")
HELP_URL("Duplex",PROP"/duplex")
HELP_URL("MDIActive",PROP"/mdiactive")
HELP_URL("MDIActiveObject",PROP"/mdiactiveobject")
HELP_URL("HintObj",PROP"/hintobj")
HELP_URL("TipObj",PROP"/tipobj")
HELP_URL("TabObj",PROP"/tabobj")
HELP_URL("MaxLength",PROP"/maxlength")
HELP_URL("Decimals",PROP"/decimals")
HELP_URL("Password",PROP"/password")
HELP_URL("ValidIfEmpty",PROP"/validifempty")
HELP_URL("ReadOnly",PROP"/readonly")
HELP_URL("FormatString",PROP"/formatstring")
HELP_URL("Changed",PROP"/changed")
HELP_URL("RTFText",PROP"/rtftext")
HELP_URL("RowTitles",PROP"/rowtitles")
HELP_URL("CurCell",PROP"/curcell")
HELP_URL("TitleWidth",PROP"/titlewidth")
HELP_URL("CellHeights",PROP"/cellheights")
HELP_URL("CellWidths",PROP"/cellwidths")
HELP_URL("TitleHeight",PROP"/titleheight")
HELP_URL("CellFonts",PROP"/cellfonts")
HELP_URL("Input",PROP"/input")
HELP_URL("Value",PROP"/value")
HELP_URL("CellTypes",PROP"/celltypes")
HELP_URL("AutoExpand",PROP"/autoexpand")
HELP_URL("CellSelect",PROP"/cellselect")
HELP_URL("ResizeRows",PROP"/resizerows")
HELP_URL("ResizeCols",PROP"/resizecols")
HELP_URL("ResizeRowTitles",PROP"/resizerowtitles")
HELP_URL("ResizeColTitles",PROP"/resizecoltitles")
HELP_URL("ClipCells",PROP"/clipcells")
HELP_URL("InputModeKey",PROP"/inputmodekey")
HELP_URL("InputMode",PROP"/inputmode")
HELP_URL("GridFCol",PROP"/gridfcol")
HELP_URL("GridBCol",PROP"/gridbcol")
HELP_URL("ShowInput",PROP"/showinput")
HELP_URL("CellSet",PROP"/cellset")
HELP_URL("RowTitleFCol",PROP"/rowtitlefcol")
HELP_URL("ColTitleFCol",PROP"/coltitlefcol")
HELP_URL("RowTitleDepth",PROP"/rowtitledepth")
HELP_URL("ColTitleDepth",PROP"/coltitledepth")
HELP_URL("RowTitleAlign",PROP"/rowtitlealign")
HELP_URL("ColTitleAlign",PROP"/coltitlealign")
HELP_URL("OverflowChar",PROP"/overflowchar")
HELP_URL("AlignChar",PROP"/alignchar")
HELP_URL("GridLineFCol",PROP"/gridlinefcol")
HELP_URL("GridLineWidth",PROP"/gridlinewidth")
//HELP_URL("GridLineStyle",PROP"/GridLineStyle")	// should this be documented?
HELP_URL("RowLineTypes",PROP"/rowlinetypes")
HELP_URL("ColLineTypes",PROP"/collinetypes")
HELP_URL("EnterReadOnlyCells",PROP"/enterreadonlycells")
HELP_URL("RowTitle3D",PROP"/rowtitle3d")
HELP_URL("ColTitle3D",PROP"/coltitle3d")
HELP_URL("RowTitleBCol",PROP"/rowtitlebcol")
HELP_URL("ColTitleBCol",PROP"/coltitlebcol")
HELP_URL("RowTreeDepth",PROP"/rowtreedepth")
HELP_URL("RowTreeStyle",PROP"/rowtreestyle")
HELP_URL("RowTreeImages",PROP"/rowtreeimages")
HELP_URL("ColSortImages",PROP"/colsortimages")
HELP_URL("SelectionColor",PROP"/selectioncolor")
HELP_URL("SelectionColorAlpha",PROP"/selectioncoloralpha")
HELP_URL("SelectionBorderWidth",PROP"/selectionborderwidth")
HELP_URL("HighlightHeaders",PROP"/highlightheaders")
HELP_URL("Translate",PROP"/translate")
HELP_URL("Accelerator",PROP"/accelerator")
#if 0
// these SHOULD be documented? Or point them to the docs for ⎕SE?
HELP_URL("CurObj",PROP"/curobj")
HELP_URL("CurWin",PROP"/curwin")
HELP_URL("CurPos",PROP"/curpos")
HELP_URL("CurSpace",PROP"/curspace")
HELP_URL("Log",PROP"/log")
#endif
HELP_URL("Popup",PROP"/popup")
//HELP_URL("IconPosn",PROP"/IconPosn")
HELP_URL("APLVersion",PROP"/aplversion")
HELP_URL("EvaluationDays",PROP"/evaluationdays")
HELP_URL("TickAlign",PROP"/tickalign")
HELP_URL("TickSpacing",PROP"/tickspacing")
HELP_URL("HasTicks",PROP"/hasticks")
HELP_URL("ShowThumb",PROP"/showthumb")
HELP_URL("TrackRect",PROP"/trackrect")
HELP_URL("ThumbRect",PROP"/thumbrect")
HELP_URL("CharFormat",PROP"/charformat")
HELP_URL("WordFormat",PROP"/wordformat")
HELP_URL("ParaFormat",PROP"/paraformat")
HELP_URL("PageWidth",PROP"/pagewidth")
//HELP_URL("EventStruct",PROP"/EventStruct")
HELP_URL("ImageCount",PROP"/imagecount")
HELP_URL("Masked",PROP"/masked")
HELP_URL("MapCols",PROP"/mapcols")
HELP_URL("CMap",PROP"/cmap")
HELP_URL("AcceptFiles",PROP"/acceptfiles")
HELP_URL("WantsReturn",PROP"/wantsreturn")
HELP_URL("MultiColumn",PROP"/multicolumn")
HELP_URL("ColumnWidth",PROP"/columnwidth")
HELP_URL("SocketType",PROP"/sockettype")
HELP_URL("SocketNumber",PROP"/socketnumber")
HELP_URL("CurrentState",PROP"/currentstate")
HELP_URL("TargetState",PROP"/targetstate")
HELP_URL("ExportedFns",PROP"/exportedfns")
HELP_URL("ExportedVars",PROP"/exportedvars")
//HELP_URL("ExportedEvents",PROP"/ExportedEvents")
HELP_URL("ClassID",PROP"/classid")
HELP_URL("Container",PROP"/container")
HELP_URL("KeepOnClose",PROP"/keeponclose")
HELP_URL("OLEControls",PROP"/olecontrols")
HELP_URL("OLEServers",PROP"/oleservers")
//HELP_URL("VerbList",PROP"/VerbList")
HELP_URL("TypeList",PROP"/typelist")
HELP_URL("HelpFile",PROP"/helpfile")
HELP_URL("ToolboxBitmap",PROP"/toolboxbitmap")
HELP_URL("LicenseKey",PROP"/licensekey")

#if 0
HELP_URL("ObjectName",PROP"/objectname")
HELP_URL("UserID",PROP"/userid")
#endif

//HELP_URL("Moniker",PROP"/Moniker")	// does this work? Should we document it?
HELP_URL("TypeLibID",PROP"/typelibid")
HELP_URL("TypeLibFile",PROP"/typelibfile")
//HELP_URL("AutoIncServerVersion",PROP"/AutoIncServerVersion") 
HELP_URL("ServerVersion",PROP"/serverversion")
HELP_URL("LastError",PROP"/lasterror")
HELP_URL("RunMode",PROP"/runmode")
HELP_URL("ShowSession",PROP"/showsession")
HELP_URL("Locale",PROP"/locale")
HELP_URL("DrawMode",PROP"/drawmode")
HELP_URL("RadiusMode",PROP"/radiusmode")
HELP_URL("AutoBrowse",PROP"/autobrowse")
HELP_URL("QueueEvents",PROP"/queueevents")
HELP_URL("MultiLine",PROP"/multiline")
HELP_URL("TabSize",PROP"/tabsize")
HELP_URL("TabJustify",PROP"/tabjustify")
HELP_URL("MultiSelect",PROP"/multiselect")
HELP_URL("TabFocus",PROP"/tabfocus")
HELP_URL("HotTrack",PROP"/hottrack")
HELP_URL("ScrollOpposite",PROP"/scrollopposite")
HELP_URL("FlatSeparators",PROP"/flatseparators")
HELP_URL("Transparent",PROP"/transparent")
HELP_URL("BandBorders",PROP"/bandborders")
HELP_URL("ChildEdge",PROP"/childedge")
HELP_URL("DblClickToggle",PROP"/dblclicktoggle")
HELP_URL("FixedOrder",PROP"/fixedorder")
HELP_URL("VariableHeight",PROP"/variableheight")
//HELP_URL("VerticalGripper",PROP"/VerticalGripper")
HELP_URL("Divider",PROP"/divider")
HELP_URL("NewLine",PROP"/newline")
//HELP_URL("FixedSize",PROP"/FixedSize")
HELP_URL("GripperMode",PROP"/grippermode")
HELP_URL("ShowCaptions",PROP"/showcaptions")
//HELP_URL("BitmapSize",PROP"/BitmapSize")
HELP_URL("ShowDropDown",PROP"/showdropdown")
HELP_URL("CheckBoxes",PROP"/checkboxes")
HELP_URL("FullRowSelect",PROP"/fullrowselect")
HELP_URL("GridLines",PROP"/gridlines")
HELP_URL("ProgressStyle",PROP"/progressstyle")
HELP_URL("SingleClickExpand",PROP"/singleclickexpand")
HELP_URL("Dockable",PROP"/dockable")
HELP_URL("Docked",PROP"/docked")
HELP_URL("DockShowCaption",PROP"/dockshowcaption")
HELP_URL("DockChildren",PROP"/dockchildren")
HELP_URL("UndocksToRoot",PROP"/undockstoroot")
#if 0
HELP_URL("AsSubForm",PROP"/assubform")
HELP_URL("AsCoolBand",PROP"/ascoolband")
#endif
HELP_URL("MaskCol",PROP"/maskcol")
HELP_URL("AlphaBlend",PROP"/alphablend")
HELP_URL("AutoPlay",PROP"/autoplay")
#if 0
HELP_URL("Redraw",PROP"/redraw")
HELP_URL("HotKey",PROP"/hotkey")
HELP_URL("Rules",PROP"/rules")
HELP_URL("DefaultModifier",PROP"/defaultmodifier")
HELP_URL("TimeUnits",PROP"/timeunits")
HELP_URL("Length",PROP"/length")
HELP_URL("Repeat",PROP"/repeat")
HELP_URL("StartPos",PROP"/startpos")
HELP_URL("AutoSizeWindow",PROP"/autosizewindow")
HELP_URL("AutoSizeMovie",PROP"/autosizemovie")
HELP_URL("MCIErrorDLG",PROP"/mcierrordlg")
HELP_URL("HaveMenu",PROP"/havemenu")
HELP_URL("HaveOpen",PROP"/haveopen")
HELP_URL("PlayBar",PROP"/playbar")
HELP_URL("ShowMode",PROP"/showmode")
HELP_URL("ShowName",PROP"/showname")
HELP_URL("ShowPos",PROP"/showpos")
HELP_URL("Zoom",PROP"/zoom")
HELP_URL("Volume",PROP"/volume")
HELP_URL("CanConfig",PROP"/canconfig")
HELP_URL("CanEject",PROP"/caneject")
HELP_URL("CanPlay",PROP"/canplay")
#endif

#if 0
HELP_URL("Timers",PROP"/timers")
HELP_URL("DebugBuild",PROP"/debugbuild")
#endif
HELP_URL("InstanceMode",PROP"/instancemode")
HELP_URL("SortItems",PROP"/sortitems")
//HELP_URL("Base",PROP"/Base")
HELP_URL("InputProperties",PROP"/inputproperties")
HELP_URL("TabIndex",PROP"/tabindex")
HELP_URL("AlwaysShowSelection",PROP"/alwaysshowselection")
HELP_URL("AlwaysShowBorder",PROP"/alwaysshowborder")
HELP_URL("ItemGroups",PROP"/itemgroups")
HELP_URL("ItemGroupMetrics",PROP"/itemgroupmetrics")
#if 0
HELP_URL("StatusWindow",PROP"/statuswindow")
HELP_URL("Editor",PROP"/editor")
HELP_URL("ScriptCompiler",PROP"/scriptcompiler")
HELP_URL("VScrollGroup",PROP"/vscrollgroup")
HELP_URL("HScrollGroup",PROP"/hscrollgroup")
#endif
//HELP_URL("FontSpacing",PROP"/FontSpacing")	// this one probably SHOULD be documented
HELP_URL("Encoding",PROP"/encoding")
HELP_URL("PageSize",PROP"/pagesize")
HELP_URL("RowHiddenDepth",PROP"/rowhiddendepth")
HELP_URL("Elevated",PROP"/elevated")
HELP_URL("Note",PROP"/note")
HELP_URL("Cue",PROP"/cue")
HELP_URL("CornerTitleBCol",PROP"/cornertitlebcol")
HELP_URL("ShowCueWhenFocused",PROP"/showcuewhenfocused")
HELP_URL("ButtonsAcceptFocus",PROP"/buttonsacceptfocus")
HELP_URL("LateBind",PROP"/latebind")
HELP_URL("HasClearButton",PROP"/hasclearbutton")
HELP_URL("AsChild",PROP"/aschild")
HELP_URL("InterceptedURLs",PROP"/interceptedurls")
HELP_URL("CEFVersion",PROP"/cefversion")
HELP_URL("MethodList",PROP"/methodlist")
HELP_URL("ChildList",PROP"/childlist")
HELP_URL("EventList",PROP"/eventlist")
HELP_URL("PropList",PROP"/proplist")
